---
language: node_js
node_js:
  - "4"

cache:
  yarn: true
  directories:
    - $HOME/.npm
    - $HOME/.cache

env:
  - TEST_SCRIPT=test:emberall
  - TEST_SCRIPT=test:node

matrix:
  fast_finish: true

before_install:
  # Since we override the install hooks, we need to setup Yarn on our own
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  # NPM & Bower need to be installed globally for ember-cli-addon-tests
  - yarn global add npm bower phantomjs-prebuilt
  - phantomjs --version

install:
  - yarn install --no-lockfile

script:
  - yarn run $TEST_SCRIPT
